---
title: "About"
---

## About me

I’m **Hanbo Dong**, a **Biostatistics PhD student at Johns Hopkins University**. My work sits at the intersection of **machine learning**, **non-parametric modeling**, and **reproducible pipelines** for biomedical data. I enjoy turning complex datasets into clear, decision-ready insights in public health and biology.


## Selected experience

- **Virome α-diversity depth correction (2024)** — Two-step quantile B-spline (with COBS) that outperforms rarefaction in sims & real data.
- **Structure-led virome annotation (2023–2024)** — AlphaFold2 + Foldseek to cluster viral proteins for function-based catalogs.
- **Longitudinal microbiome correction (2023–2024)** — Zero-inflated quantile regression models; Bayesian logistic component for separation.

---

## Publications

### Peer-reviewed
- **Dong, H.**, Li, R., Zhao, N., Dadhania, D. M., Suthanthiran, M., Lee, J. R., & Ling, W. (2024). *Antibiotic subclasses differentially perturb the gut microbiota in kidney transplant recipients.* **Frontiers in Transplantation**, 3:1400067.

### Manuscripts in preparation
- **Dong, H.**, Liu, C., Fu, C., Minot, S., & Ling, W. (2025). *Leveraging AI protein structure prediction for functional annotation of the human virome.* In preparation for submission to **Nature Microbiology**.
- **Dong, H.**, Li, M., Li, Y., Wu, M. C., & Ling, W. (2025). *Assessing α-diversity given differential read depth in virome studies via conditional quantile B-spline method.* In preparation for submission to **Nature Methods**.
- Li, S.+; **Dong, H.** +; Fu, C.+; Zhao, N.; & Ling, W. (2025). *Integration and batch correction of microbiome studies with repeated measures via longitudinal conditional quantile regression.* In preparation for submission to **Nature Methods**. (+co-first authors)

---

## Education

- **PhD, Biostatistics** — Johns Hopkins University (Expected 2029)  
- **MS, Biostatistics & Data Science** — Cornell University (Academic Excellence Award, 2024)  
- **BS, Bioprocessing of New Medicines** — University College London (First-Class Honours, 2023)

---


## Personal

Outside of research, I like **singing** (big fan of **Jay Chou**) and watching **football games**—my favorite players are **Federico Valverde** and **Son Heung-min**. Following matches helps me switch off and recharge, and it brings me a lot of fun. Music practice and weekend matches are the best ways to recharge myself so I can come back to work focused and energized.

---
